export const tableData = {
  headers: [
    {
      key: 'id',
      text: 'ID',
    },
    {
      key: 'email',
      text: 'Email',
    },
    {
      key: 'name',
      text: 'Name',
    },
    {
      key: 'lastname',
      text: 'Lastname',
    },
    {
      key: 'role',
      text: 'Role',
    },
    {
      key: 'department',
      text: 'Department',
    },
    {
      key: 'registeredOn',
      text: 'Registered on',
    },
    {
      key: 'status',
      text: 'Status',
    },
    {
      key: 'subscription',
      text: 'Subscription',
    },
  ],
  content: [
    {
      id: 1,
      email: 'kkkkopio12344@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 2,
      email: 'gegeega@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 3,
      email: 'g32g3g3g@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'free',
    },
    {
      id: 4,
      email: 'jthhhrrhr@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'free',
    },
    {
      id: 5,
      email: 'brbarfagr@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'yearly',
    },
    {
      id: 6,
      email: '32rarerfea@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 7,
      email: 'oiuiui7u98age@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 8,
      email: 'aegaeegeg@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'yearly',
    },
    {
      id: 9,
      email: 'egaegeaegeg@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 10,
      email: 'gageeegeg@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'free',
    },
    {
      id: 11,
      email: 'oooeage323@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 12,
      email: 'cccccccvveea@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 13,
      email: '3434eagge@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'monthly',
    },
    {
      id: 14,
      email: 'iiyi7y@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'free',
    },
    {
      id: 15,
      email: '98y87yhiui@gmail.com',
      name: 'John',
      lastname: 'Doe',
      role: 'Administrator',
      department: 'Angular',
      registeredOn: '23 Septemter, 2023',
      status: 'Active',
      subscriptionPlan: 'free',
    },
  ],
};
